# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Hub
tagline:          Get it started together. Quickly.
url:              http://puresol.github.io/thehub
paginate:         1
baseurl:          /
author:
  name:           Pure Solutions
  url:            http://puresolutions.com.vn
  email:          contact@puresolutions.com.vn
defaults:
  -
    scope:        
      path:       ""
    values:
      recruiter:  Pure Solutions

# Custom vars
version:          1.0.2
github:
  repo:           https://github.com/puresol/thehub
