# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Hub
tagline:          Get it started together. Quickly.
url:              http://puresol.github.io/thehub
paginate:         1
baseurl:          /
author:
  name:           Pure Solutions
  url:            http://puresolutions.com.vn
  email:          contact@puresolutions.com.vn
defaults:
  -
    scope:        
      path:       ""
    values:
      recruiter:  Pure Solutions
      cover_type: foobaz

# Custom vars
version:          1.0.3
github:
  repo:           https://github.com/puresol/thehub
disqus_id:        purebacked-thehub
livefyre_id:      374108
fb_app_id:        1436776033303812